Fix Nix errors on Travis CI
Nix on Travis CI is failing to install packages because Nixpkgs is out
of sync with Nix:

  $ nix-env --version
  nix-env (Nix) 2.0.4

  $ nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.version or lib.nixpkgsVersion'
  error: evaluation aborted with the following error message: '
  This version of Nixpkgs requires Nix >= 2.2, please upgrade:

Travis CI's Nix integration is poor anyway. Specifying a newer version
leads to failures on macOS. Avoid using Travis CI's Nix integration by
installing Nix ourselves.